sudo: required
dist: bionic
language: cpp
compiler: gcc
notifications:
  email: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-8
    - g++-8
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq qtbase5-dev qt5-qmake libqt5opengl5-dev libeigen3-dev libjpeg-dev cmake libopenvdb-tools libopenvdb-dev libopenexr-dev
install: true
script: mkdir build && cd build && cmake ../ && make -r -j 2
